name: clima
channels:
  - defaults
dependencies:
  - aom=3.6.0
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - click=8.2.1
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - expat=2.7.3
  - flask=3.1.2
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libkrb5=1.21.3
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libpq=17.6
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - numexpr=2.14.1
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openjpeg=2.5.4
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - python=3.12.12
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tornado=6.5.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - flatbuffers==25.9.23
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - namex==0.1.0
      - opt-einsum==3.4.0
      - optree==0.17.0
      - protobuf==6.33.0
      - pygments==2.19.2
      - requests==2.32.5
      - rich==14.2.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - wrapt==2.0.0
prefix: C:\Users\adria\anaconda3\envs\clima
